### PR TITLE
feat(android): Close event

### PR DESCRIPTION
**Pull request by m1ga**
**Don't merge yet**
has a bug

Test version: https://migaweb.de/ti.webdialog-android-2.0.1.zip

### CODE REVIEW

**Comment by hansemannn** [comment]
Unfortunately it's not firing for the first time.

**Comment by m1ga** [comment]
The tabs need a small warm-up time. 
Something like this
```

function openUrl(){
	var WebDialog = require('ti.webdialog');
	WebDialog.open({...});
}
```
is too short. That's why it is working the second time. The require has to be outside of the call. A `ready` event would be one way to deal with that or change the internal module structure to make it wait internally which I would prefer.

**Comment by aakash-jain-axway** [comment]
The PR works fine. package.json version bump needs to be done per the pr build error.

Also, I tried customising the code(a rough code) at my end(as mentioned in pr comment suggestion) to wait opening the url until onCustomTabsServiceConnected() is called back. It worked fine. By that the close event got fired even when the url is being opened immediately after creating module object.

**Comment by m1ga** [comment]
since it wasn't working all the time I'll close. We have to find a better way

**Comment by hansemannn** [comment]
@m1ga I noticed that we used this PR for the "close" event already. Would it be possible to open it again? I think it was solid enough

**Comment by m1ga** [comment]
@hansemannn: can't re-open it but I can add a new PR

**Pull request closed without merging**
